[project]
name = "langchain-study"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "httpx>=0.28.1",
    "icecream>=2.1.4",
    "langchain>=0.3.22",
    "langchain-openai>=0.3.12",
    "langgraph>=0.3.24",
    "pytest>=8.3.5",
    "python-dotenv>=1.1.0",
    "uvicorn[standard]>=0.34.0",
]
